hotel_homepage:
    path:     /
    defaults: { _controller: HotelBundle:Default:index }
    methods: [GET]

hotel_reservation:
    path:     /rezerwacja
    defaults: { _controller: HotelBundle:Reservation:index }
    methods: [POST]

hotel_filter:
    path:     /sprawdz
    defaults: { _controller: HotelBundle:Reservation:filter }
    methods: [POST]

hotel_rooms:
    path:     /pokoje
    defaults: { _controller: HotelBundle:Room:index }
    methods: [GET]
