hotel_homepage:
    path:     /
    defaults: { _controller: HotelBundle:Default:index }
    methods: [GET]

hotel_contact:
    path:     /kontakt
    defaults: { _controller: HotelBundle:Default:contact }
    methods: [GET]

hotel_contact_message:
    path:     /kontakt
    defaults: { _controller: HotelBundle:Default:sendMessage }
    methods: [POST]

hotel_reservation:
    path:     /rezerwacja
    defaults: { _controller: HotelBundle:Reservation:index }
    methods: [GET]

hotel_cancel_reservation:
    path:     /odwolanie-rezerwacji
    defaults: { _controller: HotelBundle:Reservation:cancel }
    methods: [GET]

hotel_filter:
    path:     /sprawdz
    defaults: { _controller: HotelBundle:Reservation:filter }
    methods: [POST]

hotel_book:
    path:     /zarezerwuj/{id}
    defaults: { _controller: HotelBundle:Reservation:book }
    methods: [POST]

hotel_create_reservation:
    path:     /zarezerwowano
    defaults: { _controller: HotelBundle:Reservation:createReservation }
    methods: [POST]

hotel_rooms:
    path:     /pokoje
    defaults: { _controller: HotelBundle:Room:index }
    methods: [GET]

hotel_rooms_show:
    path:     /szczegoly/{id}
    defaults: { _controller: HotelBundle:Room:show }
    methods: [GET]

reservation_list:
    path:     /lista-rezerwacji
    defaults: { _controller: HotelBundle:Admin:reservationList }
    methods: [GET]

restaurant:
    path:     /restauracja
    defaults: { _controller: HotelBundle:Restaurant:index }
    methods: [GET]
